language: node_js
node_js: stable
branchs:
  only:
  - hexo
cache:
    apt: true
    directories:
        - node_modules # 缓存不经常更改的内容
before_install:
# 将私钥添加到缓存
- openssl aes-256-cfb -d -in travis.key -out ~/.ssh/id_ecdsa -k ${PASS}
- chmod 600 ~/.ssh/id_ecdsa
- eval $(ssh-agent)
- ssh-add ~/.ssh/id_ecdsa
- cat known_hosts >> ~/.ssh/known_hosts

# 安装hexo-cli
- npm install -g hexo-cli


install:
# 安装依赖包
- npm install
script:
# 生成静态文件
- hexo clean
- hexo generate
after_success:
- git clone "git@github.com:liqsliu/liqsliu.github.io.git" tmp_git
- cd tmp_git
- git checkout master
- cd ../
- mv tmp_git/.git ./public/
# push到vps仓库
- cd ./public
#- git init
- git config user.name "liqsliu"
- git config user.email "liqsliu@gmail.com"
- git add .
- git commit -m "Travis CI Auto Builder"
- ssh -T git@github.com
- git push --force "git@github.com:liqsliu/liqsliu.github.io.git" master:master
- rm -rf ~/.ssh/id_ecdsa

